# Generated by Django 3.1.2 on 2020-10-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.CharField(max_length=255)),
                ('sending_contact', models.CharField(max_length=255)),
                ('receiving_contact', models.CharField(max_length=255)),
                ('box_id', models.CharField(max_length=255)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=255)),
                ('accepted_by_receiver', models.BooleanField(null=True)),
                ('transaction_state', models.CharField(choices=[('C', 'Created'), ('A', 'Accepted'), ('D', 'Denied'), ('DR', 'Dropped-Off'), ('PU', 'Picked-UP')], max_length=255)),
                ('dropoff_date', models.DateField()),
                ('pickup_date', models.DateField(null=True)),
            ],
        ),
    ]
