# Generated by Django 2.2.5 on 2020-10-31 09:59
import uuid

from django.db import migrations

from paki.models import Contacts,FavBoxes


class Migration(migrations.Migration):

    dependencies = [
        ('paki', '0003_ContactsAndFavBoxes'),
    ]

    def manual_migration(apps, schema_editor):
        julian = Contacts(contactId=uuid.uuid4(),
                          name="Julian Feinauer",
                          email="j.feinauer@pragmaticminds.de",
                          pictureLink="https://ca.slack-edge.com/T01BWJSLH9V-U01DL19HR6H-g799b8ba68f5-512"
                          )
        julian.save()

        niklas = Contacts(contactId=uuid.uuid4(),
                          name="Niklas Merz",
                          email="niklas@merz.de",
                          pictureLink="https://ca.slack-edge.com/T01BWJSLH9V-U01DGBU5TE2-9c36519a20c7-512"
                          )
        niklas.save()

        simon = Contacts(contactId=uuid.uuid4(),
                          name="Simon Mayer",
                          email="s.mayer@pragmaticminds.de",
                          pictureLink="https://ca.slack-edge.com/T01BWJSLH9V-U01DL19TLER-5cf1a6ff2c6d-512"
                          )
        simon.save()

        andreas = Contacts(contactId=uuid.uuid4(),
                         name="Andreas Schulz",
                         email="a.schulz@pragmaticminds.de",
                         pictureLink="https://ca.slack-edge.com/T01BWJSLH9V-U01ECUPTRB2-gf08513fda49-512"
                         )
        andreas.save()

        bjoern = Contacts(contactId=uuid.uuid4(),
                         name="Björn Höper",
                         email="hoerper@ltsoft.de",
                         pictureLink="https://ca.slack-edge.com/T01BWJSLH9V-U01DL1A7QNR-713807126686-512"
                         )
        bjoern.save()

        tim = Contacts(contactId=uuid.uuid4(),
                         name="Tim Mitsch",
                         email="mitsch@ltsoft.de",
                         pictureLink="https://ca.slack-edge.com/T01BWJSLH9V-U01DV8MP19S-10cccdc6fef3-512"
                         )
        tim.save()

        favbox = FavBoxes(
            boxId="bda03453-a1fd-33fb-bba4-fc570a52b124",
            contact=tim
        )
        favbox.save()

        favbox = FavBoxes(
            boxId="6ba2251b-53e2-368a-a239-ecf8871ca9d9",
            contact=tim
        )
        favbox.save()

        favbox = FavBoxes(
            boxId="5da0de41-05d2-348f-b40c-d79511198c4f",
            contact=julian
        )
        favbox.save()

        favbox = FavBoxes(
            boxId="744fed19-61da-33c2-9446-bc756c33b412",
            contact=julian
        )
        favbox.save()

        favbox = FavBoxes(
            boxId="4e7a4958-8a93-37ca-925f-b6d7efad0c39",
            contact=niklas
        )
        favbox.save()

        favbox = FavBoxes(
            boxId="26549ac8-db0c-3366-b7af-0fd85a9f23cd",
            contact=niklas
        )
        favbox.save()

        favbox = FavBoxes(
            boxId="76e1689a-37fe-333c-98bc-ee1dbc5c99ff",
            contact=simon
        )
        favbox.save()

        favbox = FavBoxes(
            boxId="c0066ac5-5696-3709-9d43-6fd1fbfafa6e",
            contact=simon
        )
        favbox.save()

        favbox = FavBoxes(
            boxId="033b5a3f-af53-3a96-b658-78f26f84d1d9",
            contact=andreas
        )
        favbox.save()

        favbox = FavBoxes(
            boxId="f12db665-72cb-3772-bc12-edad8d28b3ce",
            contact=andreas
        )
        favbox.save()

        favbox = FavBoxes(
            boxId="16a697d4-fc39-3f74-9ea4-01694573233e",
            contact=bjoern
        )
        favbox.save()

        favbox = FavBoxes(
            boxId="6c15d119-4013-38f8-847a-f15520e81734",
            contact=bjoern
        )
        favbox.save()

        # add favorites

    operations = [
        migrations.RunPython(manual_migration)
    ]


