# Generated by Django 2.2.5 on 2020-10-31 09:59
import uuid

from django.db import migrations

from paki.models import Contacts




class Migration(migrations.Migration):

    dependencies = [
        ('paki', '0003_ContactsAndFavBoxes'),
    ]

    def manual_migration(apps, schema_editor):
        julian = Contacts(contactId=uuid.uuid4(),
                          name="Julian Feinauer",
                          email="j.feinauer@pragmaticminds.de",
                          pictureLink="https://ca.slack-edge.com/T01BWJSLH9V-U01DL19HR6H-g799b8ba68f5-512"
                          )
        julian.save()

        niklas = Contacts(contactId=uuid.uuid4(),
                          name="Niklas Merz",
                          email="niklas@merz.de",
                          pictureLink="https://ca.slack-edge.com/T01BWJSLH9V-U01DGBU5TE2-9c36519a20c7-512"
                          )
        niklas.save()

        simon = Contacts(contactId=uuid.uuid4(),
                          name="Simon Mayer",
                          email="s.mayer@pragmaticminds.de",
                          pictureLink="https://ca.slack-edge.com/T01BWJSLH9V-U01DL19TLER-5cf1a6ff2c6d-512"
                          )
        simon.save()

        andreas = Contacts(contactId=uuid.uuid4(),
                         name="Andreas Schulz",
                         email="a.schulz@pragmaticminds.de",
                         pictureLink="https://ca.slack-edge.com/T01BWJSLH9V-U01ECUPTRB2-gf08513fda49-512"
                         )
        andreas.save()

        bjoern = Contacts(contactId=uuid.uuid4(),
                         name="Björn Höper",
                         email="hoerper@ltsoft.de",
                         pictureLink="https://ca.slack-edge.com/T01BWJSLH9V-U01DL1A7QNR-713807126686-512"
                         )
        bjoern.save()

        tim = Contacts(contactId=uuid.uuid4(),
                         name="Tim Mitsch",
                         email="mitsch@ltsoft.de",
                         pictureLink="https://ca.slack-edge.com/T01BWJSLH9V-U01DV8MP19S-10cccdc6fef3-512"
                         )
        tim.save()

        # add favorites

    operations = [
        migrations.RunPython(manual_migration)
    ]


