# Generated by Django 3.1.2 on 2020-10-31 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paki', '0004_initialContacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handovertransaction',
            name='receiving_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_received', to='paki.contacts'),
        ),
        migrations.AlterField(
            model_name='handovertransaction',
            name='sending_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_sent', to='paki.contacts'),
        ),
    ]
